// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  accessToken: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm9yZyI6ItCd0J7QlNCcLTQg0JcuLdCh0JjQkSDQkdCQ0KDQndCQ0KPQmyIsInVzZXJfbmFtZSI6InRlc3QiLCJpc3MiOiJodHRwOi8vMTAuMjQ4LjgyLjYwOjg5MjAvb2F1dGgvdG9rZW4iLCJub25jZSI6ImZRUzNSVXBvZDJrODJIZ1lVVVRwcGFPbzlLYlR5cmlyNWFjWU5vMWJiOWsiLCJmaW8iOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJhdXRob3JpdGllcyI6WyJQX2Rpc2tvckFkbUF1dGhfZ2V0UmlnaHRzIiwiUF9kaXNrb3JDb3JlQXBpX2VkaXRHcm91cFBvayIsIlBfZGlza29yQ29yZUFwaV9lZGl0RnVuY3Rpb24iLCJQX2Rpc2tvckFkbUF1dGhfZ2V0Um9sZXMiLCJQX2Rpc2tvckNvcmVBcGlfZWRpdFNvdXJjZUluZiIsIlBfZGlza29yQ29yZUFwaV9nZXRNZXRhUG9rIiwiUF9kaXNrb3JBZG1BdXRoX2VkaXRSaWdodCIsIlBfZGlza29yQ29yZUFwaV9lZGl0T2Zmc2V0RGF0ZSIsIlBfZGlza29yQWRtQXV0aF9lZGl0Um9sZSIsIlBfZGlza29yQ29yZUFwaV9lZGl0TnNpIiwiUF9kaXNrb3JDb3JlQXBpX2dldE51bWVyaWNQb2tWYWx1ZSIsIlBfZGlza29yQ29yZUFwaV9lZGl0UG9rVmFsdWUiLCJQX2Rpc2tvckNvcmVBcGlfZWRpdEVkSXptIiwiUF9kaXNrb3JDb3JlQXBpX2VkaXRQb2siLCJQX2Rpc2tvckNvcmVBcGlfZ2V0TnNpIiwiUF9kaXNrb3JBZG1BdXRoX2dldFVzZXJzIl0sImNsaWVudF9pZCI6ImRpc2tvciIsImF1ZCI6WyJkaXNrb3IiXSwic2NvcGUiOlsib3BlbmlkIiwicmVhZCIsIndyaXRlIl0sImV4cCI6MTYwMTk3OTk0NSwiaWF0IjoxNjAxODkzNTQ1LCJ1c2VyIjoidGVzdCIsImp0aSI6IjMxNTcwNWU4LTcwNTMtNDdlNS1iMGJhLTRjMDlhNmIwZjVhYyJ9.1TQhIwq8K_QkNYhF86WVo0mNEXDA9hRIg2C77fCby3a61tTBj0W-SSztSX9iUH7CUiNYyVpsrSpWIlz-wf7H5gsIHAgjRQeARVKEXIjo-m1G5cZy6iwDZ9q2uyUmxW3jwlkvN3APynnXvm0zX49QI_seZIudS01UebwUDT2aFhvtw7-LvQd2HNjwLp7I9oRB82YpqmXFe4NxH3RwZbVmJ2SBNkVlB89tcoxulokiTlkboyMgos8kasqNJO1h5VhIC0XQhu3wcNu8jy9SW2ELmMPIKmGDgZZsFkw8OFZgGlP7nR8nqKWG4mZmHswCI6NgP2ayemqeV2bfxujlRQBZNg',
  coreUrl: 'http://10.248.82.60:8080/diskor/core/',
  spUrl: 'http://10.248.82.60:8080/diskor/int/asoup3/sp/back/'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
